### ISSUE TITLE
作者加油！

### ISSUE THREAD

**Issue by niefufeng** [callmez/yii2-wechat#1]
本人刚学`YII2`，借鉴作者代码了！
另：坐等正式版，我把微擎换成这货！^_^

**Comment by zacksleo** [comment]
如果是Yii1，需要修改那些地方？

**Comment by callmez** [comment]
@zacksleo 暂不支持Yii1哟

**Comment by zacksleo** [comment]
好吧~不过@callmez 里面的代码写得很不错，赞一个
