### ISSUE TITLE
我可以接手维护吗?

### ISSUE THREAD

**Issue by cnjack** [callmez/yii2-wechat#16]
目前一个朋友貌似需要这个功能,但是确实太不完善了,我想接收维护项目,正好过两天我也开始有空了

**Comment by lycao** [comment]
一起吧。

**Comment by lichunqiang** [comment]
gogo

**Comment by hhao** [comment]
支持一个！

**Comment by w20968382** [comment]
我想参加这个项目开发

**Comment by w20968382** [comment]
我也是刚好在用yii微信开发

**Comment by callmez** [comment]
不用参与了 这个项目已放弃,  全新酝酿中
![image](https://cloud.githubusercontent.com/assets/1625891/15206032/997adf90-184e-11e6-92f7-d64a3b8d6ac3.png)
