### ISSUE TITLE
请问这个module如何启动，或者说是入口

### ISSUE THREAD

**Issue by rayyer** [callmez/yii2-wechat#2]
刚研究yii2，之前没用过这个框架，用的是前后台分开的高级模板Advanced Application Template，
在backend/modules下把您的代码clone了，然后在根目录的composer.json(backend父目录)里加入了"autoload": {
      "psr-4": {"callmez\wechat\": "backend/modules/wechat"}
  },
然后composer update
在后台backend的config/main.php的modules加入了'wechat' => [
            'class' => 'callmez\wechat\Module',
        ]
最后生成数据库表，创建成功。
一切都很顺利，访问index.php?r=wechat出现404，在Module.php下，我尝试输出打印，
 public function init()
    {
echo '1111';
    }
是正常的输出，应该说模块是加载成功的或者说是配置成功的，
不懂在哪去找入口或者demo,能看到你那个内置模拟器界面也可以，主要想看看怎么调用的。
tks!

**Comment by SherryJiangwei** [comment]
访问index.php?r=wechat，错误提示如下：
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: callmez\wechat\Module::adminId
……

不太明白”index.php?r=wechat/admin/account 后台里添加公众号“这句话的意思？并没有这样的入口。在数据库里手动添加数据？添加什么数据呢？

**Comment by callmez** [comment]
config.php
```
'modules' => [
      'wechat' => [
            'adminId' => '管理员UID'
      ]
]
```

**Comment by SherryJiangwei** [comment]
已经设置了该UID，甚至在数据库的Wechat表里添加了这一行的相应数据。
报错信息仍是这个：
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: callmez\wechat\Module::adminId

2. in E:\yii2\vendor\yiisoft\yii2\BaseYii.php at line 521 – yii\base\Component::__set('adminId', '1')
3. in E:\yii2\vendor\yiisoft\yii2\base\Object.php at line 105 – yii\BaseYii::configure(callmez\wechat\Module, ['modules' => ['admin' => ['class' => 'callmez\wechat\modules\admin\Mod...']], 'adminId' => '1'])
4. in E:\yii2\vendor\yiisoft\yii2\base\Module.php at line 138 – yii\base\Object::__construct(['modules' => ['admin' => ['class' => 'callmez\wechat\modules\admin\Mod...']], 'adminId' => '1'])
5. in E:\yii2\vendor\callmez\yii2-wechat\Module.php at line 58 – yii\base\Module::__construct('wechat', yii\web\Application, ['modules' => ['admin' => ['class' => 'callmez\wechat\modules\admin\Mod...']], 'adminId' => '1'])

如上

**Comment by SherryJiangwei** [comment]
补充一下……
我是在config/web.php中设置了这样的
 'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '45888RTBHG&……%#%￥',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
……

'modules' => [
        'wechat' => [ // 指定微信模块
            'class' => 'callmez\wechat\Module',
          **  'adminId' => 1 // 填写管理员ID, 该设置的用户将会拥有wechat最高权限, 如多个请填写数组 [1, 2]**
        ],
    ],

在这个配置文件下，进入index.php?r=wechat就会出现：
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: callmez\wechat\Module::adminId

**如果注释了'adminId' => 1 这行，就会出现404**


这样看来，目前我的这个项目安装无法正常进入wechat项目，无法识别adminId。

但是数据库和其他项目安装正常。
