### ISSUE TITLE
yii2-wechat 停止开发了，那 yii2-wechat-sdk 这个会继续开发吗？

### ISSUE THREAD

**Issue by luoyou** [callmez/yii2-wechat#24]
yii2-wechat-sdk 和 yii2-wechat 以及 yii2-app-wechat 之间的关系是怎样的呢？是不是 yii2-app-wechat 和 yii2-wechat 都是基于 yii2-wechat-sdk 实现的？

**Comment by callmez** [comment]
是的...都是依赖这个库, yii2-wechat-sdk 会继续开发, 但是不排除其他安排.

**Comment by ppker** [comment]
good nice
