### ISSUE TITLE
缺少文件WeChat/models/Rule.php

### ISSUE THREAD

**Issue by Surely** [callmez/yii2-wechat#6]
翻查源代码，发现您少了这个文件：use callmez\wechat\models\Rule; 这样完全没法看到效果。烦情上传之。

**Comment by callmez** [comment]
恩,代码在重构中..等我稍后补充完整代码

**Comment by Surely** [comment]
多谢，因为正在学习微信平台的开发，看到这个工具，想好好地翻一下。谢楼主开源精神
